### ISSUE TITLE
Issues in Installation

### ISSUE THREAD

**Issue by dslemusp** [UNIBO-GRABLab/cable_robot#6]
Hi

I have been trying to setup an Ethercat Master following your Installation wiki (Thanks for documenting it and sharing it :) ), but I found a couple of issues.
1. I cannot configure the ethercat-master libraries to run with the e1000e driver. It seems the kernel is too new for the current e1000e driver (I tried so far to install the latest driver and even try configuring using the flag --with-e1000e-kernel, without any luck).  
2. I tried to install it using the generic driver but that also was giving me an error, which I could solve by applying the patch in (https://www.mail-archive.com/etherlab-dev@etherlab.org/msg00522.html).

I suppose you are using a different ethernet adapter than the intel Im using, but just to let you know that there are issues with using the kernel 4.13 you guys use.

**Comment by dslemusp** [comment]
Following up on this, kernel 4.4.188 seems to be compatible with the stable-1.5 branch of the mercurial repository of ethercat-master. Kernel 3.14.79_rt85 seems to work fine with as well.

**Comment by scomari** [comment]
Hi, sorry for the late reply and thank you for your feedback.

As a matter of fact, we also apply some patches from etherlab to make it compatible with the most recent 4.13 kernel and PCIe drivers. It is included in this passage on the [Wiki/Installation](https://github.com/UNIBO-GRABLab/cable_robot/wiki/Installation) guide:

```bash
cd /usr/src
hg clone -u 33b922ec1871 http://hg.code.sf.net/p/etherlabmaster/code etherlab
hg clone http://hg.code.sf.net/u/uecasm/etherlab-patches etherlab/.hg/patches
cd etherlab
hg qpush -a
```
Please let me know if this helps.
